file=open("sample.txt","r")
text=file.read()
file.close()
old=input("Enter old text:")
new=input("Enter new text:")
text=text.replace(old,new)
file=open("sample.txt","w")
file.write(text)
file.close()
print("Text replaced")